name: PR check

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  Audit-Pull-Request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const requiredLabels = ['pixel'];
            let labels = [];

            if (context.payload.pull_request) {
              labels = context.payload.pull_request.labels;
            }

            if (labels.filter(l => requiredLabels.includes(l.name)).length === 0) {
              throw new Error(`Required labels: ${requiredLabels.join(', ')}`);
            }

  Audit-the-json-content:
    runs-on: ubuntu-latest
    needs: Audit-Pull-Request

    steps:
      - name: Checkout the PR
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Fetch base branch for comparison
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: Get the list of changed files
        id: changes
        run: |
          git diff --name-status origin/${{ github.event.pull_request.base.ref }}...${{ github.sha }} > changes.txt
          cat changes.txt

      - name: Fail if any file other than pixel_update.json is added/removed/modified
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...${{ github.sha }})
          TOTAL_FILES=$(echo "$CHANGED_FILES" | wc -l)
          
          # Check if only 'pixel_update.json' was modified
          if [[ "$TOTAL_FILES" -eq 1 ]] && [[ "$CHANGED_FILES" == "pixel_update.json" ]]; then
            echo "Only pixel_update.json was modified. Proceeding with validation..."
          else
            echo "Error: Changes found in files other than pixel_update.json. Failing the PR."
            exit 1
          fi

      - name: Save the content of changed file (pixel_update.json)
        run: |
          cat pixel_update.json > changed_file_content.txt

      - name: Pass the diff and file content to Python validation
        run: |
          python validate_pixel_update.py changes.txt changed_file_content.txt
